image: "mcr.microsoft.com/dotnet/core/sdk:3.1"

stages:
  - test
  - run

test:
  stage: test
  script:
    - dotnet test --filter TestCategory=Test

regression:
  stage: test
  script:
    - dotnet test --filter TestCategory=Regression

run:
  stage: run
  script:
    - dotnet run
